[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=15
compiler.cppstd=23
compiler.libcxx=libstdc++11

[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.build:cflags=["-std=gnu17"]

[tool_requires]
ninja/[>=1.12]
